### ISSUE TITLE
Cache/database error after snap refresh

### ISSUE THREAD

**Issue by olivercalder** [pedro-avalos/protonmail-bridge-snap#20]
Hello, revision 13 of the `protonmail-bridge` snap was released today, and after refreshing to it, I'm seeing an error message regarding the local database:

<img width="438" height="676" alt="Image" src="https://github.com/user-attachments/assets/899b9523-dd7b-4496-9244-97c8dd649751" />

I tried running the snap with `snap run protonmail-bridge`, and saw these errors in the terminal:

```
ERRO[Jul 28 16:05:52.325] Failed to apply update: failed to store message literal: open /home/oac/snap/protonmail-bridge/12/.local/share/protonmail/bridge-v3/gluon/backend/store/e58d0ee8-544a-4b0d-a899-e85c6ef812fc/b93eb650-f721-4e41-a244-a103e6a6ed21: permission denied  error="failed to store message literal: open /home/oac/snap/protonmail-bridge/12/.local/share/protonmail/bridge-v3/gluon/backend/store/e58d0ee8-544a-4b0d-a899-e85c6ef812fc/b93eb650-f721-4e41-a244-a103e6a6ed21: permission denied" pkg=gluon/user userID=e58d0ee8-544a-4b0d-a899-e85c6ef812fc
WARN[Jul 28 16:05:52.325] Failed to handle API event                    event="Event 7Kkfo3ShkIRW4e5LcA2gNgb7Bli5hM4jqPvaIYbhSqTxGLGxc-qEu8vZlhk-pc_HBJergoeEWCwmyKQ7_zGwPg==: messages: created=3, updated=6, deleted=0" service=user-events user="Nkw2XTp4kvcI9NWRra8uPfYo_1Lz-WfEoajiplgmii1S5-ARnaenyyj-A_kkUPLw_7Yp9NAEykFmHCpt__kevw=="
ERRO[Jul 28 16:05:52.325] Failed to apply event                         error="failed to handle event due to client error: failed to apply message events: failed to apply gluon update MessagesCreated: MessageCount=1 Messages=[ID:MnrQYhFfC1wwuwLTvD2ZpNsB9DWngyFQpLwD... Mailboxes:[0 5] Flags:[]]: failed to store message literal: open /home/oac/snap/protonmail-bridge/12/.local/share/protonmail/bridge-v3/gluon/backend/store/e58d0ee8-544a-4b0d-a899-e85c6ef812fc/b93eb650-f721-4e41-a244-a103e6a6ed21: permission denied" service=user-events subscriber="imap-Nkw2XTp4kvcI9NWRra8uPfYo_1Lz-WfEoajiplgmii1S5-ARnaenyyj-A_kkUPLw_7Yp9NAEykFmHCpt__kevw==" user="Nkw2XTp4kvcI9NWRra8uPfYo_1Lz-WfEoajiplgmii1S5-ARnaenyyj-A_kkUPLw_7Yp9NAEykFmHCpt__kevw=="
WARN[Jul 28 16:05:52.325] Sending info event [c2994454af664f8fbab36c82744f69e3] to mail-api.proton.me project: 7  pkg=sentry-go
WARN[Jul 28 16:05:52.555] Captured message                              message="Failed to handle event" reportID=c2994454af664f8fbab36c82744f69e3
ERRO[Jul 28 16:06:11.468] Failed to send bad event feedback             UserID="Nkw2XTp4kvcI9NWRra8uPfYo_1Lz-WfEoajiplgmii1S5-ARnaenyyj-A_kkUPLw_7Yp9NAEykFmHCpt__kevw==" doResync=true error="failed to resync imap service: failed to remove gluon users from server: failed to remove IMAP user: unlinkat /home/oac/snap/protonmail-bridge/12/.local/share/protonmail/bridge-v3/gluon/backend/store/217eb4e7-3507-46d4-b3fb-e77a56b85d65/311e57cb-d031-48df-8f44-38b2fb72f923: permission denied" pkg=grpc
```

Also, when poking around the settings, I saw that the cache directory is set to a path in `$HOME/snap/protonmail-bridge/12/...`:

<img width="1093" height="421" alt="Image" src="https://github.com/user-attachments/assets/206ef2eb-34a8-45f3-b676-a9afa93b6e63" />

I believe the problem is that the current revision is now 13, but the configuration still has paths hard-coded to revision 12.

So a migration needs to be performed as part of the snap refresh to ensure that the config paths are updated when the snap refreshes to a new revision. Or perhaps the config files can be hard-coded to use `current`, and then should be able to handle itself correctly after refreshes.

**Comment by olivercalder** [comment]
For the record, changing the "Current cache location" from `.../12/...` to `.../13/...` does fix the issue.

I don't see anything in this repo which sets the cache path. So I assume the application automatically picks it up from `$HOME` within the snap, then continues to use it and assumes the path doesn't change. So theoretically one would either need to find a way to override the default path (which I assume should be possible) and set it to `.../current/...`, or wipe the cached path after a snap refresh so that the application re-checks what `$HOME` is.

**Comment by olivercalder** [comment]
Little bit of digging around... I changed the cache path to `.../13/...` manually earlier today, but maybe other paths are still set to revision 12 even though I'm on revision 13?

```
[I] oac@fw12 ~/s/protonmail-bridge> pwd
/home/oac/snap/protonmail-bridge
[I] oac@fw12 ~/s/protonmail-bridge> rg '\/12\/' --hidden -g '!*.log'
13/.config/autostart/Proton Mail Bridge.desktop
4:Exec="/snap/protonmail-bridge/12/usr/lib/protonmail/bridge/proton-bridge" "--no-window"

12/.config/autostart/Proton Mail Bridge.desktop
4:Exec="/snap/protonmail-bridge/12/usr/lib/protonmail/bridge/proton-bridge" "--no-window"

12/.config/fontconfig/fonts.conf
2:  <dir>/snap/protonmail-bridge/12/kf6/usr/share/fonts</dir>
```

So the autostart is (which has never worked for me on the snap or flatpak for that matter). But nothing else eggregious.

In contrast, only a few things seem set up to look in `.../13/...`:

```
[I] oac@fw12 ~/s/protonmail-bridge> rg '\/13\/' --hidden -g '!*.log'
13/.config/fontconfig/fonts.conf
2:  <dir>/snap/protonmail-bridge/13/kf6/usr/share/fonts</dir>

common/.cache/gdk-pixbuf-loaders.cache
5:# LoaderDir = /snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
7:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so"
13:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so"
19:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so"
25:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so"
31:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so"
38:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so"
49:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so"
56:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so"
67:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so"
75:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so"
82:"/snap/protonmail-bridge/13/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so"
```

Notably, I don't see anything hard-coded with a revision to look in `.local/share`, so I'm not sure where that cache path is stored, yet.

**Comment by pedro-avalos** [comment]
Hey, @olivercalder thanks for letting me know about this bug. Could you help me test #21? I think that should fix it, as it overrides the environment variables that Proton Mail Bridge uses

**Comment by pedro-avalos** [comment]
Since I don't use the bridge often enough to keep it installed my workstation. I actually install it fresh when I'm testing it, so I didn't catch the bug; I suspect this has been around a while...

**Comment by olivercalder** [comment]
I'll give it a try, thanks!

**Comment by olivercalder** [comment]
Hmm, so I built the snap from your `fix-paths` branch, and installed it (rev `x1`), and the snap seems to still show that `.../13/...` is used as the cache:

<img width="1080" height="388" alt="Image" src="https://github.com/user-attachments/assets/46f4663a-8cc8-479e-9506-6e8ca987ce40" />

And now I sent myself an email (from my phone) and it caused the same internal error message when it tried to write to the database:

<img width="421" height="655" alt="Image" src="https://github.com/user-attachments/assets/60024ffa-26e5-4122-b757-9313115b3820" />

However, all the environment variables seem to be set correctly:

```
# snap run --shell protonmail-bridge
oac@fw12:~$ env | grep '\/13\/'
oac@fw12:~$ env | grep '\/12\/'
oac@fw12:~$ env | grep '\/x1\/'
__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS=/snap/protonmail-bridge/x1/gpu-2404/usr/share/egl/egl_external_platform.d
__EGL_VENDOR_LIBRARY_DIRS=/snap/protonmail-bridge/x1/gpu-2404/usr/share/glvnd/egl_vendor.d
XDG_CONFIG_DIRS=/snap/protonmail-bridge/x1/kf6/etc/xdg:/home/oac/.config
QT_XKB_CONFIG_ROOT=/snap/protonmail-bridge/x1/kf6/usr/share/X11/xkb
VK_LAYER_PATH=/snap/protonmail-bridge/x1/gpu-2404/usr/share/vulkan/implicit_layer.d/:/snap/protonmail-bridge/x1/gpu-2404/usr/share/vulkan/explicit_layer.d/
QTCOMPOSE=/snap/protonmail-bridge/x1/kf6/usr/share/X11/locale
FONTCONFIG_PATH=/snap/protonmail-bridge/x1/kf6/etc/fonts
KF6_LIBEXEC_DIR=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/libexec/kf6
XDG_DATA_HOME=/home/oac/snap/protonmail-bridge/x1/.local/share
PIPEWIRE_MODULE_DIR=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/pipewire-0.3
XDG_CONFIG_HOME=/home/oac/snap/protonmail-bridge/x1/.config
XCURSOR_PATH=/snap/protonmail-bridge/x1/data-dir/icons:/snap/protonmail-bridge/x1/kf6/usr/share/icons
ALSA_CONFIG_PATH=/snap/protonmail-bridge/x1/kf6/etc/asound.conf
SPA_PLUGIN_DIR=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/spa-0.2
GST_PLUGIN_SCANNER=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
GI_TYPELIB_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/girepository-1.0
QTWEBENGINEPROCESS_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/qt6/libexec/QtWebEngineProcess
DRIRC_CONFIGDIR=/snap/protonmail-bridge/x1/gpu-2404/drirc.d
SNAP_DESKTOP_RUNTIME=/snap/protonmail-bridge/x1/kf6
PIPEWIRE_CONFIG_DIR=/snap/protonmail-bridge/x1/kf6/usr/share/pipewire
LIBGWEATHER_LOCATIONS_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/libgweather-4/Locations.bin
XLOCALEDIR=/snap/protonmail-bridge/x1/gpu-2404/X11/locale
LIBTHAI_DICTDIR=/snap/protonmail-bridge/x1/kf6/usr/share/libthai/
GDK_PIXBUF_MODULEDIR=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
LOCPATH=/snap/protonmail-bridge/x1/kf6/usr/lib/locale
LIBGL_DRIVERS_PATH=/snap/protonmail-bridge/x1/gpu-2404/usr/lib/x86_64-linux-gnu/dri/:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/i386-linux-gnu/dri/
GST_PLUGIN_PATH=/snap/protonmail-bridge/x1/usr/lib/x86_64-linux-gnu/gstreamer-1.0
QML2_IMPORT_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/qt6/qml:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/qml
XDG_STATE_HOME=/home/oac/snap/protonmail-bridge/x1/.local/state
LD_LIBRARY_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu:/snap/protonmail-bridge/x1/kf6/usr/lib:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/protonmail-bridge/x1/usr/lib:/snap/protonmail-bridge/x1/usr/lib/x86_64-linux-gnu:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/x86_64-linux-gnu:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/x86_64-linux-gnu/vdpau:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/i386-linux-gnu:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/i386-linux-gnu/vdpau:/snap/protonmail-bridge/x1/kf6/lib/x86_64-linux-gnu:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu:/snap/protonmail-bridge/x1/kf6/usr/lib:/snap/protonmail-bridge/x1/kf6/lib:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/libproxy:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/blas:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/lapack
LIBVA_DRIVERS_PATH=/snap/protonmail-bridge/x1/gpu-2404/usr/lib/x86_64-linux-gnu/dri/:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/i386-linux-gnu/dri/
GST_PLUGIN_SYSTEM_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/gstreamer-1.0
VLC_PLUGIN_PATH=/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/vlc/plugins
FONTCONFIG_FILE=/snap/protonmail-bridge/x1/kf6/etc/fonts/fonts.conf
GBM_BACKENDS_PATH=/snap/protonmail-bridge/x1/gpu-2404/usr/lib/x86_64-linux-gnu/gbm:/snap/protonmail-bridge/x1/gpu-2404/usr/lib/i386-linux-gnu/gbm
XDG_DATA_DIRS=/home/oac/snap/protonmail-bridge/x1/.local/share:/home/oac/snap/protonmail-bridge/x1:/snap/protonmail-bridge/x1/data-dir:/snap/protonmail-bridge/x1/usr/share:/snap/protonmail-bridge/x1/kf6/usr/share:/home/oac/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/snap/protonmail-bridge/x1/gpu-2404/usr/share
PATH=/snap/protonmail-bridge/x1/usr/sbin:/snap/protonmail-bridge/x1/usr/bin:/snap/protonmail-bridge/x1/sbin:/snap/protonmail-bridge/x1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/protonmail-bridge/x1/kf6/usr/bin
QT_PLUGIN_PATH=/snap/protonmail-bridge/x1/usr/lib/x86_64-linux-gnu:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/qt6/plugins:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/plugins:/snap/protonmail-bridge/x1/kf6/usr/lib/x86_64-linux-gnu/
XKB_CONFIG_ROOT=/snap/protonmail-bridge/x1/kf6/usr/share/X11/xkb
```

So it seems that the problem is that this cache path is not actually set based on the environment variable.
